// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pyjvvwfsodogcxpedpdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5anZ2d2Zzb2RvZ2N4cGVkcGRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0Mzk2NDQsImV4cCI6MjA3MzAxNTY0NH0.aiUwA5lZNtDfOrXgjLPt5XYdfT6sQza5c29-IVJN1uM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});